// (function($){
//     $(document).ready(function(){
//         $('.form-box').hide();
//         $('.fa-chevron-down').click(function(){
//             $('.form-box').slideDown(100);
//         });
//         $('.fa-times-circle').click(function(){
//             $('.form-box').slideUp(100);
//         });
//     });
// })(jQuery)